# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nWE3bSoAbBZzqCXbcg6dIFcTI0wZiyVb
"""

from transformers import AutoTokenizer, AutoModelForCausalLM

models = {
    "0.5B": "Qwen/Qwen2.5-0.5B-Instruct",
    "1.5B": "Qwen/Qwen2.5-1.5B-Instruct",
    "3B": "Qwen/Qwen2.5-3B-Instruct",
    "7B": "Qwen/Qwen2.5-7B-Instruct",
    "14B": "Qwen/Qwen2.5-14B-Instruct",
}

def load_model(model_name):
    print(f"Loading: {model_name}")

    tokenizer = AutoTokenizer.from_pretrained(model_name)

    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        device_map="auto"
    )

    parameters = sum(p.numel() for p in model.parameters())

    print(f"Parameters: {parameters:,}")
    print("Loaded successfully!\n")

    return tokenizer, model

tokenizer, model = load_model(models["0.5B"])

print(model)

print(model.config)

print("Hidden size:", model.config.hidden_size)
print("Layers:", model.config.num_hidden_layers)
print("Attention heads:", model.config.num_attention_heads)
print("Vocabulary size:", model.config.vocab_size)

prompt = "Explain how a CNC machine works."

inputs = tokenizer(
    prompt,
    return_tensors="pt"
).to(model.device)

outputs = model.generate(
    **inputs,
    max_new_tokens=100
)

response = tokenizer.decode(
    outputs[0],
    skip_special_tokens=True
)

print(response)

import time
import torch

prompt = "Explain how a CNC machine works."

inputs = tokenizer(
    prompt,
    return_tensors="pt"
).to(model.device)

start = time.perf_counter()

outputs = model.generate(
    **inputs,
    max_new_tokens=100
)

end = time.perf_counter()

elapsed = end - start

generated_tokens = outputs.shape[1] - inputs["input_ids"].shape[1]

tokens_per_second = generated_tokens / elapsed

print(f"Generated tokens: {generated_tokens}")
print(f"Time: {elapsed:.2f} seconds")
print(f"Tokens/sec: {tokens_per_second:.2f}")

tokenizer, model = load_model(models["1.5B"])

tokenizer, model = load_model(models["3B"])

model_name = "Qwen/Qwen2.5-7B-Instruct"

tokenizer, model = load_model(model_name)

