# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nWE3bSoAbBZzqCXbcg6dIFcTI0wZiyVb
"""

from transformers import AutoTokenizer, AutoModelForCausalLM

models = {
    "0.5B": "Qwen/Qwen2.5-0.5B-Instruct",
    "1.5B": "Qwen/Qwen2.5-1.5B-Instruct",
    "3B": "Qwen/Qwen2.5-3B-Instruct",
    "7B": "Qwen/Qwen2.5-7B-Instruct",
    "14B": "Qwen/Qwen2.5-14B-Instruct",
}

def load_model(model_name):
    print(f"Loading: {model_name}")

    tokenizer = AutoTokenizer.from_pretrained(model_name)

    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        device_map="auto"
    )

    parameters = sum(p.numel() for p in model.parameters())

    print(f"Parameters: {parameters:,}")
    print("Loaded successfully!\n")

    return tokenizer, model

tokenizer, model = load_model(models["0.5B"])

print(model)

print(model.config)

print("Hidden size:", model.config.hidden_size)
print("Layers:", model.config.num_hidden_layers)
print("Attention heads:", model.config.num_attention_heads)
print("Vocabulary size:", model.config.vocab_size)

prompt = "Explain how a CNC machine works."

inputs = tokenizer(
    prompt,
    return_tensors="pt"
).to(model.device)

outputs = model.generate(
    **inputs,
    max_new_tokens=100
)

response = tokenizer.decode(
    outputs[0],
    skip_special_tokens=True
)

print(response)

import time
import torch

prompt = "Explain how a CNC machine works."

inputs = tokenizer(
    prompt,
    return_tensors="pt"
).to(model.device)

start = time.perf_counter()

outputs = model.generate(
    **inputs,
    max_new_tokens=100
)

end = time.perf_counter()

elapsed = end - start

generated_tokens = outputs.shape[1] - inputs["input_ids"].shape[1]

tokens_per_second = generated_tokens / elapsed

print(f"Generated tokens: {generated_tokens}")
print(f"Time: {elapsed:.2f} seconds")
print(f"Tokens/sec: {tokens_per_second:.2f}")

tokenizer, model = load_model(models["1.5B"])

tokenizer, model = load_model(models["3B"])

model_name = "Qwen/Qwen2.5-7B-Instruct"

tokenizer, model = load_model(model_name)


from transformers import AutoConfig
import pandas as pd

def inspect_model(size, model_name):
    config = AutoConfig.from_pretrained(model_name)

    width = config.hidden_size
    layers = config.num_hidden_layers
    heads = config.num_attention_heads
    kv_heads = config.num_key_value_heads
    mlp_width = config.intermediate_size
    vocabulary = config.vocab_size
    head_dimension = width // heads

    # Rough transformer scaling measurement
    complexity = layers * width**2

    return {
        "Model": size,
        "Layers": layers,
        "Hidden width": width,
        "Attention heads": heads,
        "KV heads": kv_heads,
        "Head dimension": head_dimension,
        "MLP width": mlp_width,
        "Vocabulary": vocabulary,
        "L × D²": complexity,
    }


results = [
    inspect_model(size, model_name)
    for size, model_name in models.items()
]

comparison = pd.DataFrame(results)
comparison


baseline = comparison.loc[0, "L × D²"]

comparison["Relative complexity"] = (
    comparison["L × D²"] / baseline
).round(2)

comparison



!pip install -q -U transformers accelerate pandas

import gc
import time
import torch
import pandas as pd

from transformers import (
    AutoConfig,
    AutoTokenizer,
    AutoModelForCausalLM,
)

models = {
    "0.5B": "Qwen/Qwen2.5-0.5B-Instruct",
    "1.5B": "Qwen/Qwen2.5-1.5B-Instruct",
    "3B": "Qwen/Qwen2.5-3B-Instruct",
    "7B": "Qwen/Qwen2.5-7B-Instruct",
    "14B": "Qwen/Qwen2.5-14B-Instruct",
}


architecture_results = []

for size, model_name in models.items():
    config = AutoConfig.from_pretrained(model_name)

    architecture_results.append({
        "Model": size,
        "Layers": config.num_hidden_layers,
        "Hidden width": config.hidden_size,
        "Attention heads": config.num_attention_heads,
        "KV heads": config.num_key_value_heads,
        "Head dimension":
            config.hidden_size // config.num_attention_heads,
        "MLP width": config.intermediate_size,
        "Vocabulary": config.vocab_size,
    })

architecture_table = pd.DataFrame(architecture_results)
architecture_table

def benchmark_model(
    model_name,
    prompt="Explain how a CNC machine works.",
    max_new_tokens=100,
):
    print(f"Loading {model_name}")

    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        torch.cuda.reset_peak_memory_stats()

    tokenizer = AutoTokenizer.from_pretrained(model_name)

    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        dtype="auto",
        device_map="auto",
    )

    model.eval()

    messages = [
        {"role": "user", "content": prompt}
    ]

    formatted_prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
    )

    input_device = next(model.parameters()).device

    inputs = tokenizer(
        formatted_prompt,
        return_tensors="pt",
    ).to(input_device)

    input_tokens = inputs["input_ids"].shape[1]

    # Short warm-up generation
    with torch.inference_mode():
        model.generate(
            **inputs,
            max_new_tokens=5,
            do_sample=False,
            use_cache=True,
        )

    if torch.cuda.is_available():
        torch.cuda.synchronize()
        torch.cuda.reset_peak_memory_stats()

    start = time.perf_counter()

    with torch.inference_mode():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            use_cache=True,
        )

    if torch.cuda.is_available():
        torch.cuda.synchronize()

    elapsed = time.perf_counter() - start
    generated_tokens = outputs.shape[1] - input_tokens
    tokens_per_second = generated_tokens / elapsed

    parameter_count = sum(
        parameter.numel()
        for parameter in model.parameters()
    )

    peak_memory_gb = (
        torch.cuda.max_memory_allocated() / 1e9
        if torch.cuda.is_available()
        else 0
    )

    generated_text = tokenizer.decode(
        outputs[0, input_tokens:],
        skip_special_tokens=True,
    )

    result = {
        "Parameters": parameter_count,
        "Generated tokens": generated_tokens,
        "Seconds": elapsed,
        "Tokens/sec": tokens_per_second,
        "Peak GPU memory (GB)": peak_memory_gb,
    }

    del outputs, inputs, model, tokenizer
    gc.collect()

    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    return result, generated_text


result, response = benchmark_model(models["0.5B"])

print(result)
print("\nResponse:")
print(response)

models_to_test = ["0.5B", "1.5B", "3B"]

benchmark_results = []

for size in models_to_test:
    try:
        result, _ = benchmark_model(models[size])

        benchmark_results.append({
            "Model": size,
            **result,
        })

    except torch.cuda.OutOfMemoryError:
        print(f"{size} did not fit in GPU memory.")

        gc.collect()
        torch.cuda.empty_cache()

benchmark_table = pd.DataFrame(benchmark_results)
benchmark_table




