"""Lower the scheduled operations to readable, shape-specialized C."""

def emit_c(graph, kernels) -> str:
    batch, width = graph[0].shape
    by_name = {node.name: node for node in graph}
    functions = []
    for kernel in kernels:
        signature = ", ".join(
            [f"const float *restrict {name}" for name in kernel.inputs]
            + [f"float *restrict {kernel.output}"]
        )
        operations = tuple(by_name[name].operation for name in kernel.operations)
        if operations in (("matmul_transpose",),
                          ("matmul_transpose", "add_bias", "relu")):
            if operations == ("matmul_transpose",):
                finish = "Z[b * WIDTH + row] = sum;"
            else:
                finish = ("float value = sum + bias[row];\n"
                          "      Y[b * WIDTH + row] = value > 0.0f ? value : 0.0f;")
            body = """  for (size_t b = 0; b < BATCH; ++b) {
    for (size_t row = 0; row < WIDTH; ++row) {
      float sum = 0.0f;
      for (size_t col = 0; col < WIDTH; ++col) {
        sum += X[b * WIDTH + col] * W[row * WIDTH + col];
      }
      FINISH
    }
  }""".replace("FINISH", finish)
        elif operations == ("add_bias",):
            body = """  for (size_t i = 0; i < BATCH * WIDTH; ++i) {
    A[i] = Z[i] + bias[i % WIDTH];
  }"""
        elif operations == ("relu",):
            body = """  for (size_t i = 0; i < BATCH * WIDTH; ++i) {
    Y[i] = A[i] > 0.0f ? A[i] : 0.0f;
  }"""
        else:
            raise ValueError(f"unsupported kernel operations: {operations}")
        functions.append(f"void {kernel.name}({signature}) {{\n{body}\n}}")
    return ("/* Generated by compiler-practice/codegen.py. FP32 CPU kernels. */\n"
            "#include <stddef.h>\n"
            f"#define WIDTH ((size_t){width})\n#define BATCH ((size_t){batch})\n\n"
            + "\n\n".join(functions) + "\n")
